[package]
name = "fai"
version = "0.1.0"
authors = ["Devyn Cairns <devyn.cairns@gmail.com>"]

[lib]

[dependencies]
lazy_static = "0.2"
byteorder = "1.0"
getopts = "0.2"
log = "0.3"
env_logger = "0.4"
termion = "1.3"

[dependencies.nom]
version = "2.2"
features = ["verbose-errors"]
